# ============================================================
# ShellIA - AppVeyor CI/CD Configuration
# ============================================================
version: 1.0.{build}

image:
  - Ubuntu

configuration: Release
platform: Any CPU

environment:
  DOCKER_USER:
    secure: cFiYnLsRXfGJQUACN3B9ag==
  DOCKER_PASS:
    secure: 7p0MUOkaQMGwpEolyRITrcObvCNd6qjbvd5us2QScHKEqZmcHzFPGkd5Muq3UVvG
  matrix:
    - ARCH: amd64

build_script:
  - ps: ./.appveyor/build.ps1

test_script:
  - ps: ./.appveyor/test.ps1

deploy_script:
  - ps: ./.appveyor/deploy.ps1
